### ISSUE TITLE
Type undefined when seeding deep nesting of related models

### ISSUE THREAD

**Issue by oflynned** [Luidog/marpat#20]
Context:
I have a complex dataset that essentially is compromised of such:
repayment -> loan -> community member -> community fund -> project -> user

I have been creating factories to seed the relevant upper levels as necessary for tests and fixtures, however when I try to seed a community member, calling `CommunityMember.create(payload).save()` results in `CommunityMember` having just `_id` in the schema (there should be many more) and `type` being undefined. By seeding a community member, it in turn seeds a fund with any other related things, then a project, then a user. It seems to work for all things above this level.

From what I can see, it looks like it's either me reaching a connection issue, or something in the `Document` class not being instantiated. Models are not linked as being embedded documents, they are instead linked by just the class type as a field.

Weirdly enough, it works up to the point of community funds.

Here's the stacktrace:
```
TypeError: Cannot read property 'type' of undefined

    at normalizeType (/home/ed/Desktop/Projects/Consultancy/GreenFi/GreenFi-Web/node_modules/marpat/lib/base-document.js:20:16)
    at /home/ed/Desktop/Projects/Consultancy/GreenFi/GreenFi-Web/node_modules/marpat/lib/base-document.js:117:25
    at Array.forEach (<anonymous>)
    at CommunityFund.generateSchema (/home/ed/Desktop/Projects/Consultancy/GreenFi/GreenFi-Web/node_modules/marpat/lib/base-document.js:110:18)
    at Function._instantiate (/home/ed/Desktop/Projects/Consultancy/GreenFi/GreenFi-Web/node_modules/marpat/lib/base-document.js:331:14)
    at Function.createIndexes (/home/ed/Desktop/Projects/Consultancy/GreenFi/GreenFi-Web/node_modules/marpat/lib/document.js:368:25)
    at Function.create (/home/ed/Desktop/Projects/Consultancy/GreenFi/GreenFi-Web/node_modules/marpat/lib/base-document.js:311:10)
    at create (/home/ed/Desktop/Projects/Consultancy/GreenFi/GreenFi-Web/test/factories/communityFundFactory.js:51:28)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

Looking at a breakpoint in-depth and instantiating with `new CommunityFund()`, it looks like there's nothing in `_schema` aside from `_id`, and it looks like the schema I wrote is not loaded in. It looks like even though a type is set in the schema, it is assigned "undefined.

```
CommunityMember {
      _schema: { _id: { type: [Function] } },
      _id: null,
      createdAt:
       { type: [Function: Date],
         default: 1570632304158,
         required: true },
      updatedAt: [Function: Date],
      name: { type: [Function: String], required: true },
      dob:
       { type: [Function: String],
         match: /([12]\d{3}-(0[1-9]|[12]\d|3[01])-(0[1-9]|1[0-2]))/,
         required: true },
      sex:
       { type: [Function: String],
         choices: [ 'male', 'female' ],
         required: true },
      livelihood: { type: [Function: String], required: true },
      governmentIdNumber: { type: [Function: String], required: true },
      governmentIdPhoto: { type: [Function: String], default: null, required: false },
      memberPhoto: { type: [Function: String], default: null, required: false },
      telephoneNumber: { type: [Function: String], min: 1, required: true },
      organisationalPosition:
       { type: [Function: String],
         choices: [ 'chairman', 'treasurer', 'secretary', 'member' ],
         required: true },
      communityFund: { type: undefined, required: true },
      lat: { type: [Function: Number], required: true },
      lng: { type: [Function: Number], required: true } }
```

Update: commenting out `CommunityFund` from the `CommunityMember` schema stops the error from being thrown, but then there's no access to the higher-order components. Same happens when I try to set `createdBy` on the `User` schema with another user.

**Comment by Luidog** [comment]
@oflynned Thank you for raising this issue and for providing details. Would you be able to provide the schema for community member and community funds?

From what you describe it sounds like the child document is not being instantiated and saved before the parent document is saved. If this is the issue I would suggest using the preInit() hook to create and save the child document before the parent document is saved.  

Seeing the schema for each document will help.

**Comment by Luidog** [comment]
@oflynned Thank you for the schemas. 

I think you are right about the `preInit(...)` method. I had assumed that the child document was not created.

This project does allow cyclical dependencies that are tested [here] (https://github.com/Luidog/marpat/blob/master/test/documents/cyclical.test.js).

May I ask what datastore you are using in this project? 

if you can add me to your repo so I can reproduce the issue myself and see the tests you created that would be very helpful.

**Comment by oflynned** [comment]
@Luidog I'm using a MongoDB datastore. I added you to a mirror repo, the latest on `master` should be the right commit point. Have a look at `test/marpat.test.js` for generating some models to reproduce the issues with linking models.

**Comment by Luidog** [comment]
@oflynned I noticed in the CommunityFund schema that chairman, treasurer, and secretary were not defined with a type. The schema definition for a document property that is another document should look like this:

```javascript
  chairman: {
    type: CommunityMember
  },
  treasurer: {
    type: CommunityMember
  },
  secretary: {
    type: CommunityMember
  }
```

In the example, the schema properties of chairman, treasurer, and secretary have the parent document as their type.  This small change should prevent the issue you are seeing.

A document's schema property must declare a type.

As you mentioned, the project you originally referenced has a complex dataset. I had trouble getting the tests to the project you invited me to collaborate on to pass. However, I can see based on the logging in [marpat.test.js](https://github.com/oflynned/GreenFi-Web-Marpat-Issue/blob/master/test/marpat.test.js) that CommunityFund documents are now created correctly.   Please make the suggested schema updates and close this issue if we have solved the problem.

**Comment by oflynned** [comment]
@Luidog Thanks for taking a look at that. That's interesting that it's working for you, as when I make the required changes for declaring schema property types, I get a validation error. 
```
...
  createdBy: {
    type: User
  },
...
```
For example, on setting the `createdBy` property by passing in a user object to `seedUser` which should allow both undefined and a user value:
```
ValidationError: Value assigned to users.createdBy should be undefined, got object
```

**Comment by Luidog** [comment]
@oflynned I think your last comment raises a different issue than what we were working on previously.

I found that the communityMember and communityFund documents were created properly in [marpat.test.js](https://github.com/oflynned/GreenFi-Web-Marpat-Issue/blob/934b0ce25a7e9ae6b92d1ed6d2c0397f19efc2f0/test/marpat.test.js#L8-L32).

Once the [communityFund](https://github.com/oflynned/GreenFi-Web-Marpat-Issue/blob/master/src/models/communityFund/schema.js) schema properties of chairman, treasurer, and secretary are updated to specify the [communityMember](https://github.com/oflynned/GreenFi-Web-Marpat-Issue/blob/master/src/models/communityMember/schema.js) class as the type for each property the instances are created correctly.

The additional issue you mentioned in your last comment sounds related to the [user schema](https://github.com/oflynned/GreenFi-Web-Marpat-Issue/blob/934b0ce25a7e9ae6b92d1ed6d2c0397f19efc2f0/src/models/user/schema.js#L30-L32). The [createUser function](https://github.com/oflynned/GreenFi-Web-Marpat-Issue/blob/934b0ce25a7e9ae6b92d1ed6d2c0397f19efc2f0/src/controllers/userController.js#L28-L47) does not find or instantiate a User for the createdBy property. There should be an additional line between lines 43 and 44 of the [userController](https://github.com/oflynned/GreenFi-Web-Marpat-Issue/blob/master/src/controllers/userController.js) that finds or creates or a User instance which will be embedded in the createdBy property. I would expect the seedUser function to look something like this:

```javascript
export const createUser = async ({ user: { _id, ...originalUser }, body }, shouldGeneratePassword = true) => {
  ...
  const createdBy = User.find({_id}).then(user => user ? user : User.create(originalUser).save())
  const payload = Object.assign({}, body, { hash, createdBy });
  const account = await User.create(payload).save();
  ...
};
```

I appreciate you adding me to your repository and I want to want to get these issue identified and resolved for you. I am having trouble parsing the complexity of the tests in the repository you shared. To expedite solving these issues would it be possible to create a minimal test or two that could be added to the marpat repository to showcase each issue? If we can focus on a simplified schema that still exposes the issue it would go a long way toward resolving each issue.

**side note:** _I noticed when looking through the User document definition that the document is designed to support end users. I created another project which you might find very useful alongside marpat. The project is [passport-marpat-local](https://github.com/Luidog/passport-local-marpat#readme). It is designed to simplify creation of server accounts and hashing of server user credentials using [passport.js](http://www.passportjs.org)._

**Comment by Luidog** [comment]
@oflynned I appreciate you raising this issue. I believe the issues you mentioned are resolved. If the issues still persist please comment on this issue and I will reopen it.

If the issues are not resolved using the techniques I mentioned in this issue thread I would ask you to create a minimal test that can be added to the marpat repo to showcase the issue.

**Comment by Luidog** [comment]
@oflynned did my last comment help you?

**Comment by oflynned** [comment]
@Luidog Apologies for not getting back to you, your comments helped to resolve things! Thank you so much for taking the time to help me.

**Comment by Luidog** [comment]
@oflynned It is my pleasure. Please reach out if you have any other issues.
