### ISSUE TITLE
Hot to aggregate in marpat?

### ISSUE THREAD

**Issue by SettingDust** [Luidog/marpat#23]
I want to sort with a String field length. Hot to use size in marpat?

**Comment by Luidog** [comment]
@SettingDust This project provides a wrapper around nedb and MongoDB with the ability to add a custom datastore client as required.

If you are using marpat in-memory or via the filesystem you can use [nedb's sorting syntax](https://github.com/louischatriot/nedb#sorting-and-paginating)

If you are using MongoDB you can use [mongodb's cursor sort](https://docs.mongodb.com/manual/reference/method/cursor.sort/#cursor.sort)
