### ISSUE TITLE
Why Marpat?

### ISSUE THREAD

**Issue by jaspersorrio** [Luidog/marpat#33]
Hi @Luidog great project! Will try using Marpat in my new projects.

However I'm curious on how you arrived on the name Marpat. Care to share more?

**Comment by Luidog** [comment]
Hey @jaspersorrio,

Thank you for the compliment. I appreciate it. 

This project was a fork of another project [camo](https://github.com/scottwrobinson/camo). Camo is short for camouflage. Marpat is short for [Marine Pattern](https://en.wikipedia.org/wiki/MARPAT), which is a type of camouflage. I chose the name marpat to honor the work of the original contributors.
