### ISSUE TITLE
Bug within postFind

### ISSUE THREAD

**Issue by a-christie** [Luidog/marpat#34]
I noticed that this line:
`postFindPromises.concat(docs._getHookPromises('postFind'));` in [document.js](https://github.com/Luidog/marpat/blob/master/lib/document.js#L292) ignores the hook promises and just moves on because Array.concat doesn't edit an array in place. If I correct the line to `postFindPromises = postFindPromises.concat(docs._getHookPromises('postFind'));` then the promises get executed correctly before `Class.findOne(..)` returns.
Is this intentional and if so why?

**Comment by Luidog** [comment]
Hey @a-christie, Thank you. This was unintentional. Would you mind submitting a PR?

**Comment by a-christie** [comment]
Sure, here you go: `https://github.com/Luidog/marpat/pull/35`

**Comment by Luidog** [comment]
Thank you for the PR @a-christie. It will be included in the next release if the test pass when running internally.
