### ISSUE TITLE
Add support for DynamoDB

### ISSUE THREAD

**Issue by cimbura** [Luidog/marpat#8]
https://aws.amazon.com/dynamodb/

**Comment by Luidog** [comment]
@cimbura  Thank you for raising this issue. I looked into DynamoDB a bit and found that you must create a table schema before adding any documents. I am not sure how this would work with this project.

If you have a specific use case you think would make this a good fit I am open to it. If you want to submit a PR containing a DynamoDB client or you want to sponsor the work towards a marpat / DynamoDB integration I am open to either of those.

I am going to close this issue for now. If you would like to discuss this further please send me message.
